theme: jekyll-theme-slate
header_pages: 
  - home
  - contact

landclear_slideshow: 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_001.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_002.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_003.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_004.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_005.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_006.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_007.jpeg 
- https://raw.githubusercontent.com/heywoodlh/dldirtworks/master/images/land-clearing-cabin-pad/signal-2022-01-16-163723_008.jpeg 
