theme: jekyll-theme-slate

header_pages: 
  - home
  - contact

carousels:
  - images:
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_001.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_002.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_003.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_004.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_005.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_006.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_007.jpeg 
    - ./images/land-clearing-cabin-pad/signal-2022-01-16-163723_008.jpeg 
  - images:
    - ./images/basement-excavation/signal-2022-01-16-164212_001.jpeg
    - ./images/basement-excavation/signal-2022-01-16-164212_002.jpeg
  - images:
    - ./images/utilities-geothermal/signal-2022-01-16-164809_001.jpeg
    - ./images/utilities-geothermal/signal-2022-01-16-164809_002.jpeg
    - ./images/utilities-geothermal/signal-2022-01-16-164809_003.jpeg
    - ./images/utilities-geothermal/signal-2022-01-16-164809_004.jpeg
    - ./images/utilities-geothermal/signal-2022-01-16-164809_005.jpeg
